"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.options3 import Options3


class TestOptions3(unittest.TestCase):
    """Options3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptions3(self):
        """Test Options3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Options3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
