"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_entity_types_response import ListEntityTypesResponse


class TestListEntityTypesResponse(unittest.TestCase):
    """ListEntityTypesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEntityTypesResponse(self):
        """Test ListEntityTypesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListEntityTypesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
