"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.retrieve_entity_response import RetrieveEntityResponse


class TestRetrieveEntityResponse(unittest.TestCase):
    """RetrieveEntityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRetrieveEntityResponse(self):
        """Test RetrieveEntityResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RetrieveEntityResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
