"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_or_append_entity_attributes_request import UpdateOrAppendEntityAttributesRequest


class TestUpdateOrAppendEntityAttributesRequest(unittest.TestCase):
    """UpdateOrAppendEntityAttributesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateOrAppendEntityAttributesRequest(self):
        """Test UpdateOrAppendEntityAttributesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateOrAppendEntityAttributesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
