"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.types_api import TypesApi  # noqa: E501


class TestTypesApi(unittest.TestCase):
    """TypesApi unit test stubs"""

    def setUp(self):
        self.api = TypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_entity_types(self):
        """Test case for list_entity_types

        List Entity Types  # noqa: E501
        """
        pass

    def test_retrieve_entity_type(self):
        """Test case for retrieve_entity_type

        Retrieve entity type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
