"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.api_entry_point_api import APIEntryPointApi  # noqa: E501


class TestAPIEntryPointApi(unittest.TestCase):
    """APIEntryPointApi unit test stubs"""

    def setUp(self):
        self.api = APIEntryPointApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_api_resources(self):
        """Test case for retrieve_api_resources

        Retrieve API Resources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
