"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.attributes_api import AttributesApi  # noqa: E501


class TestAttributesApi(unittest.TestCase):
    """AttributesApi unit test stubs"""

    def setUp(self):
        self.api = AttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attribute_data(self):
        """Test case for get_attribute_data

        Get attribute data  # noqa: E501
        """
        pass

    def test_remove_a_single_attribute(self):
        """Test case for remove_a_single_attribute

        Remove a Single Attribute  # noqa: E501
        """
        pass

    def test_update_attribute_data(self):
        """Test case for update_attribute_data

        Update Attribute Data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
