"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.options6 import Options6


class TestOptions6(unittest.TestCase):
    """Options6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptions6(self):
        """Test Options6"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Options6()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
