"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_registration_request import UpdateRegistrationRequest


class TestUpdateRegistrationRequest(unittest.TestCase):
    """UpdateRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateRegistrationRequest(self):
        """Test UpdateRegistrationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateRegistrationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
