"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.subscriptions_api import SubscriptionsApi  # noqa: E501


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        Create Subscription  # noqa: E501
        """
        pass

    def test_delete_subscription(self):
        """Test case for delete_subscription

        Delete subscription  # noqa: E501
        """
        pass

    def test_list_subscriptions(self):
        """Test case for list_subscriptions

        List Subscriptions  # noqa: E501
        """
        pass

    def test_retrieve_subscription(self):
        """Test case for retrieve_subscription

        Retrieve Subscription  # noqa: E501
        """
        pass

    def test_update_subscription(self):
        """Test case for update_subscription

        Update Subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
