"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.entities_api import EntitiesApi  # noqa: E501


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self):
        self.api = EntitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_entity(self):
        """Test case for create_entity

        Create Entity  # noqa: E501
        """
        pass

    def test_list_entities(self):
        """Test case for list_entities

        List Entities  # noqa: E501
        """
        pass

    def test_remove_entity(self):
        """Test case for remove_entity

        Remove Entity  # noqa: E501
        """
        pass

    def test_replace_all_entity_attributes(self):
        """Test case for replace_all_entity_attributes

        Replace all entity attributes  # noqa: E501
        """
        pass

    def test_retrieve_entity(self):
        """Test case for retrieve_entity

        Retrieve Entity  # noqa: E501
        """
        pass

    def test_retrieve_entity_attributes(self):
        """Test case for retrieve_entity_attributes

        Retrieve Entity Attributes  # noqa: E501
        """
        pass

    def test_update_existing_entity_attributes(self):
        """Test case for update_existing_entity_attributes

        Update Existing Entity Attributes  # noqa: E501
        """
        pass

    def test_update_or_append_entity_attributes(self):
        """Test case for update_or_append_entity_attributes

        Update or Append Entity Attributes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
