"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_entity_request import CreateEntityRequest


class TestCreateEntityRequest(unittest.TestCase):
    """CreateEntityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateEntityRequest(self):
        """Test CreateEntityRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateEntityRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
