"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_registration_request import CreateRegistrationRequest


class TestCreateRegistrationRequest(unittest.TestCase):
    """CreateRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRegistrationRequest(self):
        """Test CreateRegistrationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateRegistrationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
