"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_entities_response import ListEntitiesResponse


class TestListEntitiesResponse(unittest.TestCase):
    """ListEntitiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEntitiesResponse(self):
        """Test ListEntitiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListEntitiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
