"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.options12 import Options12


class TestOptions12(unittest.TestCase):
    """Options12 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptions12(self):
        """Test Options12"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Options12()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
