"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.registrations_api import RegistrationsApi  # noqa: E501


class TestRegistrationsApi(unittest.TestCase):
    """RegistrationsApi unit test stubs"""

    def setUp(self):
        self.api = RegistrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_registration(self):
        """Test case for create_registration

        Create Registration  # noqa: E501
        """
        pass

    def test_delete_registration(self):
        """Test case for delete_registration

        Delete Registration  # noqa: E501
        """
        pass

    def test_list_registrations(self):
        """Test case for list_registrations

        List Registrations  # noqa: E501
        """
        pass

    def test_retrieve_registration(self):
        """Test case for retrieve_registration

        Retrieve Registration  # noqa: E501
        """
        pass

    def test_update_registration(self):
        """Test case for update_registration

        Update Registration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
