"""
    FIWARE-NGSI v2 Specification

    TODO: Add a description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.batch_operations_api import BatchOperationsApi  # noqa: E501


class TestBatchOperationsApi(unittest.TestCase):
    """BatchOperationsApi unit test stubs"""

    def setUp(self):
        self.api = BatchOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notify(self):
        """Test case for notify

        Notify  # noqa: E501
        """
        pass

    def test_query(self):
        """Test case for query

        Query  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
